"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useUNLINK = exports.useText = exports.useResolve = exports.usePUT = exports.usePURGE = exports.usePOST = exports.usePATCH = exports.useOPTIONS = exports.useMutate = exports.useLoading = exports.useLINK = exports.useImperative = exports.useHEAD = exports.useGql = exports.useGET = exports.useFetcher = exports.useFetchId = exports.useFetch = exports.useError = exports.useData = exports.useDELETE = exports.useConfig = exports.useCode = exports.useBlob = exports.setURLParams = exports.revalidate = exports.queryProvider = exports.mutateData = exports.gql = exports.SSRSuspense = exports.FetcherConfig = void 0;
var http_react_1 = require("http-react");
Object.defineProperty(exports, "FetcherConfig", { enumerable: true, get: function () { return http_react_1.FetcherConfig; } });
Object.defineProperty(exports, "SSRSuspense", { enumerable: true, get: function () { return http_react_1.SSRSuspense; } });
Object.defineProperty(exports, "gql", { enumerable: true, get: function () { return http_react_1.gql; } });
Object.defineProperty(exports, "mutateData", { enumerable: true, get: function () { return http_react_1.mutateData; } });
Object.defineProperty(exports, "queryProvider", { enumerable: true, get: function () { return http_react_1.queryProvider; } });
Object.defineProperty(exports, "revalidate", { enumerable: true, get: function () { return http_react_1.revalidate; } });
Object.defineProperty(exports, "setURLParams", { enumerable: true, get: function () { return http_react_1.setURLParams; } });
Object.defineProperty(exports, "useBlob", { enumerable: true, get: function () { return http_react_1.useBlob; } });
Object.defineProperty(exports, "useCode", { enumerable: true, get: function () { return http_react_1.useCode; } });
Object.defineProperty(exports, "useConfig", { enumerable: true, get: function () { return http_react_1.useConfig; } });
Object.defineProperty(exports, "useDELETE", { enumerable: true, get: function () { return http_react_1.useDELETE; } });
Object.defineProperty(exports, "useData", { enumerable: true, get: function () { return http_react_1.useData; } });
Object.defineProperty(exports, "useError", { enumerable: true, get: function () { return http_react_1.useError; } });
Object.defineProperty(exports, "useFetch", { enumerable: true, get: function () { return http_react_1.useFetch; } });
Object.defineProperty(exports, "useFetchId", { enumerable: true, get: function () { return http_react_1.useFetchId; } });
Object.defineProperty(exports, "useFetcher", { enumerable: true, get: function () { return http_react_1.useFetcher; } });
Object.defineProperty(exports, "useGET", { enumerable: true, get: function () { return http_react_1.useGET; } });
Object.defineProperty(exports, "useGql", { enumerable: true, get: function () { return http_react_1.useGql; } });
Object.defineProperty(exports, "useHEAD", { enumerable: true, get: function () { return http_react_1.useHEAD; } });
Object.defineProperty(exports, "useImperative", { enumerable: true, get: function () { return http_react_1.useImperative; } });
Object.defineProperty(exports, "useLINK", { enumerable: true, get: function () { return http_react_1.useLINK; } });
Object.defineProperty(exports, "useLoading", { enumerable: true, get: function () { return http_react_1.useLoading; } });
Object.defineProperty(exports, "useMutate", { enumerable: true, get: function () { return http_react_1.useMutate; } });
Object.defineProperty(exports, "useOPTIONS", { enumerable: true, get: function () { return http_react_1.useOPTIONS; } });
Object.defineProperty(exports, "usePATCH", { enumerable: true, get: function () { return http_react_1.usePATCH; } });
Object.defineProperty(exports, "usePOST", { enumerable: true, get: function () { return http_react_1.usePOST; } });
Object.defineProperty(exports, "usePURGE", { enumerable: true, get: function () { return http_react_1.usePURGE; } });
Object.defineProperty(exports, "usePUT", { enumerable: true, get: function () { return http_react_1.usePUT; } });
Object.defineProperty(exports, "useResolve", { enumerable: true, get: function () { return http_react_1.useResolve; } });
Object.defineProperty(exports, "useText", { enumerable: true, get: function () { return http_react_1.useText; } });
Object.defineProperty(exports, "useUNLINK", { enumerable: true, get: function () { return http_react_1.useUNLINK; } });
