export type { CacheStoreType, FetchInit } from "http-react"

export {
  Client,
  FetchConfig,
  SSRSuspense,
  gql,
  mutateData,
  queryProvider,
  revalidate,
  setURLParams,
  useBlob,
  useCode,
  useConfig,
  useDELETE,
  useData,
  useError,
  useFetchId,
  useGET,
  useGql,
  useHEAD,
  useImperative,
  useLINK,
  useLoading,
  useMutate,
  useOPTIONS,
  usePATCH,
  usePOST,
  usePURGE,
  usePUT,
  useResolve,
  useText,
  useUNLINK,
} from "http-react"

export { default } from "http-react"
